name: 'Get & Cache Dependencies'
description: 'Composite action for Cached dependencies steps'
inputs:
  my-option:
    #description: 'setting up optional input'
    required: false
    default: 'true'
outputs:
  option-given:
    #description: 'setting up output'
    value: ${{ steps.install.outputs.caching }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.my-option == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.my-option != 'true'
      run: | 
        npm install --no-audit --no-fund
        run: echo "caching= '${{ inputs.my-option }}'">> $GITHUB_OUTPUT
      shell: bash